dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "sipf-github"
    token:
      secure: "aRveMjllXUbopmHC80zfVZxh+kfquAYAyD7kgydmciltgH7tC+lCNCw6oBPg+7IXieyESAlgGIs3oAmKMFwvHJWAn6ntM4XVBWDRbI1dD/ar3/DkP/caYduTNxZoSqfYst1QtoB9W41ehJdoJFI/ZGAwE+LHvwqje6Qel9ixabkISoqsfy83yxs3i8JRy3HC0HJfXnw0+F+HKehi96RWxovnxD5wm7cxwAmsuaF+un+5t1+LE32GPKjpfJhGrRCABwfIRH2xkp9n0vMRLl2Eu8HqaDY/cPlk4OdK5avjHTs44U3nAXil6fboE0YXvJIEu3ElQaKNFj4wfX5VrPt2c88DDHlck++I4EukhxiwamP+ppcg9KEHAx+gUCfKfXlKjRkqdqtPAkTUqz3UK9It+aJgPwkAY6Twcx8ztEKdWW5z4inz/UnO+h795JJPw6NjAB8WGPrwfQ0rlwUCUrUysXhquSFjK/82DuhYCFQ5S9PBSiAQ/kA+oOtbcyajrbtAFG+HoTkzXUCVGhC/oYVsuSNCnOA/nbvMtypfNCNLDsZZTMSClo+tLi6xnQbYVOI/8P4t9i/tyNaxDR+5F1juf7hBcgpDDQ+rx6fErHBIxMKXWMuKJPXM1sBjtx/KYSsANXxWlh38hqdRzDFW3m6vrT9IeqbHVXHKySl3f05C2Fg="


jdk:
 - oraclejdk8

script:
  - mvn package
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
